module.exports = {
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROFILE_VIEWED: "PROFILE_VIEWED",
  PROFILE_BANNER_UPDATED: "PROFILE_BANNER_UPDATED",
  PROFILE_PICTURE_UPDATED: "PROFILE_PICTURE_UPDATED",
};